package fullhousedb;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author adeliae
 */
public class Keuzemenu extends javax.swing.JFrame {

    /**
     * Creates new form Keuzemenu
     */
    public Keuzemenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keuzePanel = new javax.swing.JPanel();
        overzichtPanel = new javax.swing.JPanel();
        text3 = new javax.swing.JLabel();
        spelerinPanel = new javax.swing.JPanel();
        beschrijving1 = new javax.swing.JLabel();
        spelerbwPanel = new javax.swing.JPanel();
        text4 = new javax.swing.JLabel();
        toerinPanel = new javax.swing.JPanel();
        beschrijving = new javax.swing.JLabel();
        toerbwPanel = new javax.swing.JPanel();
        text2 = new javax.swing.JLabel();
        masterinPanel = new javax.swing.JPanel();
        beschrijving2 = new javax.swing.JLabel();
        masterbwPanel = new javax.swing.JPanel();
        text6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        beschrijving3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        text5 = new javax.swing.JLabel();
        spelerAddT = new javax.swing.JPanel();
        text7 = new javax.swing.JLabel();
        spelerAddM = new javax.swing.JPanel();
        text11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        keuzePanel.setBackground(new java.awt.Color(224, 224, 224));

        overzichtPanel.setBackground(new java.awt.Color(228, 228, 228));
        overzichtPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overzichtPanelMouseClicked(evt);
            }
        });

        text3.setText("Overzicht");

        javax.swing.GroupLayout overzichtPanelLayout = new javax.swing.GroupLayout(overzichtPanel);
        overzichtPanel.setLayout(overzichtPanelLayout);
        overzichtPanelLayout.setHorizontalGroup(
            overzichtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overzichtPanelLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        overzichtPanelLayout.setVerticalGroup(
            overzichtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overzichtPanelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(text3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spelerinPanel.setBackground(new java.awt.Color(228, 228, 228));
        spelerinPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spelerinPanelMouseClicked(evt);
            }
        });

        beschrijving1.setText("Speler toevoegen");

        javax.swing.GroupLayout spelerinPanelLayout = new javax.swing.GroupLayout(spelerinPanel);
        spelerinPanel.setLayout(spelerinPanelLayout);
        spelerinPanelLayout.setHorizontalGroup(
            spelerinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spelerinPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(beschrijving1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        spelerinPanelLayout.setVerticalGroup(
            spelerinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spelerinPanelLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(beschrijving1)
                .addGap(28, 28, 28))
        );

        spelerbwPanel.setBackground(new java.awt.Color(228, 228, 228));
        spelerbwPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spelerbwPanelMouseClicked(evt);
            }
        });

        text4.setText("Speler bewerken / verwijderen");

        javax.swing.GroupLayout spelerbwPanelLayout = new javax.swing.GroupLayout(spelerbwPanel);
        spelerbwPanel.setLayout(spelerbwPanelLayout);
        spelerbwPanelLayout.setHorizontalGroup(
            spelerbwPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spelerbwPanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        spelerbwPanelLayout.setVerticalGroup(
            spelerbwPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spelerbwPanelLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(text4)
                .addGap(25, 25, 25))
        );

        toerinPanel.setBackground(new java.awt.Color(228, 228, 228));
        toerinPanel.setPreferredSize(new java.awt.Dimension(187, 75));
        toerinPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toerinPanelMouseClicked(evt);
            }
        });

        beschrijving.setText("Toernooi aanmaken");

        javax.swing.GroupLayout toerinPanelLayout = new javax.swing.GroupLayout(toerinPanel);
        toerinPanel.setLayout(toerinPanelLayout);
        toerinPanelLayout.setHorizontalGroup(
            toerinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toerinPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(beschrijving, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        toerinPanelLayout.setVerticalGroup(
            toerinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toerinPanelLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(beschrijving)
                .addGap(26, 26, 26))
        );

        toerbwPanel.setBackground(new java.awt.Color(228, 228, 228));
        toerbwPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toerbwPanelMouseClicked(evt);
            }
        });

        text2.setText("Toernooi bewerken / verwijderen");

        javax.swing.GroupLayout toerbwPanelLayout = new javax.swing.GroupLayout(toerbwPanel);
        toerbwPanel.setLayout(toerbwPanelLayout);
        toerbwPanelLayout.setHorizontalGroup(
            toerbwPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toerbwPanelLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        toerbwPanelLayout.setVerticalGroup(
            toerbwPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toerbwPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(text2)
                .addGap(28, 28, 28))
        );

        masterinPanel.setBackground(new java.awt.Color(228, 228, 228));
        masterinPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterinPanelMouseClicked(evt);
            }
        });

        beschrijving2.setText("Masterclass aanmaken");

        javax.swing.GroupLayout masterinPanelLayout = new javax.swing.GroupLayout(masterinPanel);
        masterinPanel.setLayout(masterinPanelLayout);
        masterinPanelLayout.setHorizontalGroup(
            masterinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masterinPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(beschrijving2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        masterinPanelLayout.setVerticalGroup(
            masterinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masterinPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(beschrijving2)
                .addGap(35, 35, 35))
        );

        masterbwPanel.setBackground(new java.awt.Color(228, 228, 228));
        masterbwPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterbwPanelMouseClicked(evt);
            }
        });

        text6.setText("Masterclass bewerken / verwijderen");

        javax.swing.GroupLayout masterbwPanelLayout = new javax.swing.GroupLayout(masterbwPanel);
        masterbwPanel.setLayout(masterbwPanelLayout);
        masterbwPanelLayout.setHorizontalGroup(
            masterbwPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masterbwPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(text6, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        masterbwPanelLayout.setVerticalGroup(
            masterbwPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masterbwPanelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(text6)
                .addGap(33, 33, 33))
        );

        jPanel1.setBackground(new java.awt.Color(228, 228, 228));

        beschrijving3.setText("Aanmaken / inschrijven");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(beschrijving3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(beschrijving3)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(228, 228, 228));

        text5.setText("Bewerken / verwijderen");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(text5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spelerAddT.setBackground(new java.awt.Color(228, 228, 228));
        spelerAddT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spelerAddTMouseClicked(evt);
            }
        });

        text7.setText("Speler inschrijven voor toernooi");

        javax.swing.GroupLayout spelerAddTLayout = new javax.swing.GroupLayout(spelerAddT);
        spelerAddT.setLayout(spelerAddTLayout);
        spelerAddTLayout.setHorizontalGroup(
            spelerAddTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spelerAddTLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(text7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        spelerAddTLayout.setVerticalGroup(
            spelerAddTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spelerAddTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(text7)
                .addGap(25, 25, 25))
        );

        spelerAddM.setBackground(new java.awt.Color(228, 228, 228));
        spelerAddM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spelerAddMMouseClicked(evt);
            }
        });

        text11.setText("Speler inschrijven voor masterclass");

        javax.swing.GroupLayout spelerAddMLayout = new javax.swing.GroupLayout(spelerAddM);
        spelerAddM.setLayout(spelerAddMLayout);
        spelerAddMLayout.setHorizontalGroup(
            spelerAddMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spelerAddMLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(text11, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        spelerAddMLayout.setVerticalGroup(
            spelerAddMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spelerAddMLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(text11)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout keuzePanelLayout = new javax.swing.GroupLayout(keuzePanel);
        keuzePanel.setLayout(keuzePanelLayout);
        keuzePanelLayout.setHorizontalGroup(
            keuzePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keuzePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(keuzePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(keuzePanelLayout.createSequentialGroup()
                        .addGroup(keuzePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spelerinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toerinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(masterinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36))
                    .addGroup(keuzePanelLayout.createSequentialGroup()
                        .addGroup(keuzePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spelerAddM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spelerAddT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)))
                .addGroup(keuzePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spelerbwPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toerbwPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masterbwPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(overzichtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        keuzePanelLayout.setVerticalGroup(
            keuzePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keuzePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(keuzePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overzichtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(keuzePanelLayout.createSequentialGroup()
                        .addGroup(keuzePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(keuzePanelLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spelerinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toerinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(keuzePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(keuzePanelLayout.createSequentialGroup()
                                .addComponent(spelerbwPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toerbwPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(masterbwPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(keuzePanelLayout.createSequentialGroup()
                                .addComponent(masterinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(spelerAddT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spelerAddM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(keuzePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(keuzePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void overzichtPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overzichtPanelMouseClicked
        setVisible(false);                  
        JFrame frame = new Overzicht(); //gaat naar overzicht
        frame.setVisible(true);
    }//GEN-LAST:event_overzichtPanelMouseClicked

    private void spelerinPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spelerinPanelMouseClicked
        JFrame frame = new InschrijvenSpeler(); //opent nieuwe venster speler toevoegen
        frame.setVisible(true);
        frame.setTitle("Nieuwe speler aanmaken");
    }//GEN-LAST:event_spelerinPanelMouseClicked

    private void toerinPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toerinPanelMouseClicked
        JFrame frame = new ToernooiAanmaken(); //opent nieuwe venster toernooi aanmaken
        frame.setVisible(true);
        frame.setTitle("Nieuwe toernooi aanmaken");
    }//GEN-LAST:event_toerinPanelMouseClicked

    private void masterinPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterinPanelMouseClicked
        JFrame frame = new MasterclassAanmaken(); //opent nieuwe venster masterclass aanmaken
        frame.setVisible(true);
        frame.setTitle("Nieuwe masterclass aanmaken");
    }//GEN-LAST:event_masterinPanelMouseClicked

    private void toerbwPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toerbwPanelMouseClicked
        setVisible(false);                  
        JFrame frame = new ToernooiBewerken(); //bewerk toernooien
        frame.setVisible(true);
    }//GEN-LAST:event_toerbwPanelMouseClicked

    private void masterbwPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterbwPanelMouseClicked
        setVisible(false);                  
        JFrame frame = new MasterclassBewerken(); //bewerk masterclasses
        frame.setVisible(true);
    }//GEN-LAST:event_masterbwPanelMouseClicked

    private void spelerbwPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spelerbwPanelMouseClicked
        setVisible(false);                  
        JFrame frame = new SpelerBewerken(); //bewerk speler
        frame.setVisible(true);
    }//GEN-LAST:event_spelerbwPanelMouseClicked

    private void spelerAddTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spelerAddTMouseClicked
        JFrame frame = new InschrijvenT(); //inschrijven toernooien
        frame.setVisible(true);
    }//GEN-LAST:event_spelerAddTMouseClicked

    private void spelerAddMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spelerAddMMouseClicked
        JFrame frame = new InschrijvenM(); //inschrijven masterclasses
        frame.setVisible(true);
    }//GEN-LAST:event_spelerAddMMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beschrijving;
    private javax.swing.JLabel beschrijving1;
    private javax.swing.JLabel beschrijving2;
    private javax.swing.JLabel beschrijving3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel keuzePanel;
    private javax.swing.JPanel masterbwPanel;
    private javax.swing.JPanel masterinPanel;
    private javax.swing.JPanel overzichtPanel;
    private javax.swing.JPanel spelerAddM;
    private javax.swing.JPanel spelerAddT;
    private javax.swing.JPanel spelerbwPanel;
    private javax.swing.JPanel spelerinPanel;
    private javax.swing.JLabel text11;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text6;
    private javax.swing.JLabel text7;
    private javax.swing.JPanel toerbwPanel;
    private javax.swing.JPanel toerinPanel;
    // End of variables declaration//GEN-END:variables
}
