package fullhousedb;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adeliae
 */
public class MasterclassBewerken extends javax.swing.JFrame {

    /**
     * Creates new form Aanmaken
     */
    public MasterclassBewerken() {
        initComponents();
        this.HaalTabelOp();
    }
    
    public void HaalTabelOp(){
        String query = "SELECT * FROM Masterclass";
         Database db = new Database();
        try {
            mcTabel.setModel(db.getFromDatabase(query));
        } catch (SQLException ex) {
            Logger.getLogger(MasterclassBewerken.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientPanel = new javax.swing.JPanel();
        menuClient = new javax.swing.JButton();
        bewerk = new javax.swing.JButton();
        tabelPane = new javax.swing.JScrollPane();
        mcTabel = new javax.swing.JTable();
        verwijder = new javax.swing.JButton();
        date = new org.jdesktop.swingx.JXDatePicker();
        naam = new javax.swing.JTextField();
        soort = new javax.swing.JTextField();
        niveau = new javax.swing.JTextField();
        maxsp = new javax.swing.JTextField();
        minr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clientPanel.setBackground(new java.awt.Color(228, 228, 228));
        clientPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Masterclasses bewerken"));
        clientPanel.setToolTipText("");

        menuClient.setText("Terug");
        menuClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientActionPerformed(evt);
            }
        });

        bewerk.setText("Bewerken");
        bewerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bewerkActionPerformed(evt);
            }
        });

        mcTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mcTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mcTabelMouseClicked(evt);
            }
        });
        tabelPane.setViewportView(mcTabel);

        verwijder.setText("Verwijderen");
        verwijder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verwijderActionPerformed(evt);
            }
        });

        jLabel1.setText("Naam:");

        jLabel2.setText("Soort:");

        jLabel3.setText("Niveau:");

        jLabel4.setText("Max Spelers:");

        jLabel5.setText("Min Rating:");

        jLabel6.setText("Datum:");

        jLabel9.setText("id:");

        id.setEditable(false);

        javax.swing.GroupLayout clientPanelLayout = new javax.swing.GroupLayout(clientPanel);
        clientPanel.setLayout(clientPanelLayout);
        clientPanelLayout.setHorizontalGroup(
            clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientPanelLayout.createSequentialGroup()
                .addComponent(menuClient)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(clientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelPane, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bewerk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verwijder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(clientPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clientPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(minr)
                                    .addComponent(maxsp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(niveau, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soort, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(naam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientPanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(155, Short.MAX_VALUE))))
        );
        clientPanelLayout.setVerticalGroup(
            clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientPanelLayout.createSequentialGroup()
                .addComponent(menuClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientPanelLayout.createSequentialGroup()
                        .addComponent(tabelPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(clientPanelLayout.createSequentialGroup()
                        .addComponent(bewerk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verwijder)
                        .addGap(68, 68, 68)
                        .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(naam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(niveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientActionPerformed
        setVisible(false);
        JFrame frame = new Keuzemenu(); //gaat terug naar keuzemenu
        frame.setVisible(true);
    }//GEN-LAST:event_menuClientActionPerformed

    private void bewerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bewerkActionPerformed
        Database db = new Database();
        int max = Integer.parseInt(maxsp.getText()); //zet string om naar int
        int min = Integer.parseInt(minr.getText());
        int mcid = Integer.parseInt(id.getText());
        
        try {
            db.updateMClass(naam.getText(), date.getDate(), soort.getText(), niveau.getText(), max, min, mcid);
        } catch (SQLException ex) {
            Logger.getLogger(InschrijvenSpeler.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.HaalTabelOp();
    }//GEN-LAST:event_bewerkActionPerformed

    private void verwijderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verwijderActionPerformed
        int row = mcTabel.getSelectedRow();
        String klas = String.valueOf(mcTabel.getValueAt(row, 1)); //haalt waarde van rij op
        
        Database db = new Database();
        String query = "DELETE FROM Masterclass "
                + "WHERE naam = '" + klas + " '";
        try {        
            db.verwijderRij(query);
        } catch (SQLException ex) {
            Logger.getLogger(SpelerBewerken.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.HaalTabelOp();
    }//GEN-LAST:event_verwijderActionPerformed

    private void mcTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mcTabelMouseClicked
        String mid = mcTabel.getValueAt(mcTabel.getSelectedRow(), 0).toString();
        String naam1 = mcTabel.getValueAt(mcTabel.getSelectedRow(), 1).toString(); //haalt individuele waardes van kolommen op
        String plts = mcTabel.getValueAt(mcTabel.getSelectedRow(), 3).toString();
        String srt = mcTabel.getValueAt(mcTabel.getSelectedRow(), 4).toString();
        String rnd = mcTabel.getValueAt(mcTabel.getSelectedRow(), 5).toString();
        String max = mcTabel.getValueAt(mcTabel.getSelectedRow(), 6).toString();

        id.setText(mid);
        naam.setText(naam1); //en zet deze in een aparte textlabel
        soort.setText(plts);
        niveau.setText(srt);
        maxsp.setText(rnd);
        minr.setText(max);
    }//GEN-LAST:event_mcTabelMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bewerk;
    private javax.swing.JPanel clientPanel;
    private org.jdesktop.swingx.JXDatePicker date;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField maxsp;
    private javax.swing.JTable mcTabel;
    private javax.swing.JButton menuClient;
    private javax.swing.JTextField minr;
    private javax.swing.JTextField naam;
    private javax.swing.JTextField niveau;
    private javax.swing.JTextField soort;
    private javax.swing.JScrollPane tabelPane;
    private javax.swing.JButton verwijder;
    // End of variables declaration//GEN-END:variables
}
